<?xml version="1.0" encoding="utf-8"?><Database Name="qlBanHang" Class="DataClasses3DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-FMKHDML\SQLEXPRESS;Initial Catalog=qlBanHang;Integrated Security=True" SettingsObjectName="QuanLyBanHang.Properties.Settings" SettingsPropertyName="qlBanHangConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTiet_HDBan" Member="ChiTiet_HDBans">
    <Type Name="ChiTiet_HDBan">
      <Column Name="MaHD" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiamGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="HDBan_ChiTiet_HDBan" Member="HDBan" ThisKey="MaHD" OtherKey="MaHD" Type="HDBan" IsForeignKey="true" />
      <Association Name="NhapKho_ChiTiet_HDBan" Member="NhapKho" ThisKey="MaSP" OtherKey="MaSP" Type="NhapKho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.XuatKho" Member="XuatKhos">
    <Type Name="XuatKho">
      <Column Name="MaQuay" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenQuay" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaSP" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="SoLuongXuat" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="NhapKho_XuatKho" Member="NhapKho" ThisKey="MaSP" OtherKey="MaSP" Type="NhapKho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonVi" Member="DonVis">
    <Type Name="DonVi">
      <Column Name="MaDV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DonVi_NhapKho" Member="NhapKhos" ThisKey="MaDV" OtherKey="MaDV" Type="NhapKho" />
    </Type>
  </Table>
  <Table Name="dbo.HDBan" Member="HDBans">
    <Type Name="HDBan">
      <Column Name="MaHD" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HDBan_ChiTiet_HDBan" Member="ChiTiet_HDBan" ThisKey="MaHD" OtherKey="MaHD" Type="ChiTiet_HDBan" Cardinality="One" />
      <Association Name="NhanVien_HDBan" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NCC" Member="NCCs">
    <Type Name="NCC">
      <Column Name="MaNCC" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NCC_NhapKho" Member="NhapKhos" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhapKho" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaQuyen" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Association Name="NhanVien_HDBan" Member="HDBans" ThisKey="MaNV" OtherKey="MaNV" Type="HDBan" />
      <Association Name="Quyen_NhanVien" Member="Quyen" ThisKey="MaQuyen" OtherKey="MaQuyen" Type="Quyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhapKho" Member="NhapKhos">
    <Type Name="NhapKho">
      <Column Name="MaSP" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaDV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="GiaNhap" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SoLuongNhap" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="NhapKho_ChiTiet_HDBan" Member="ChiTiet_HDBans" ThisKey="MaSP" OtherKey="MaSP" Type="ChiTiet_HDBan" />
      <Association Name="NhapKho_XuatKho" Member="XuatKhos" ThisKey="MaSP" OtherKey="MaSP" Type="XuatKho" />
      <Association Name="DonVi_NhapKho" Member="DonVi" ThisKey="MaDV" OtherKey="MaDV" Type="DonVi" IsForeignKey="true" />
      <Association Name="NCC_NhapKho" Member="NCC" ThisKey="MaNCC" OtherKey="MaNCC" Type="NCC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Quyen" Member="Quyens">
    <Type Name="Quyen">
      <Column Name="MaQuyen" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenQuyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Quyen_NhanVien" Member="NhanViens" ThisKey="MaQuyen" OtherKey="MaQuyen" Type="NhanVien" />
    </Type>
  </Table>
</Database>